webdriver.driver = chrome
webdriver.autodownload = false
serenity.browser.maximized = true

headless.mode=false
serenity.dry.run=false
serenity.use.unique.browser=true

chrome.switches= --incognito; --ignore-certificate-errors; --disable-dev-shm-usage; --window-size=1920,1080
#chrome.switches= --headless, --start-maximized, --ignore-certificate-errors, --disable-dev-shm-usage
drivers.windows.webdriver.chrome.driver=src/test/resources/driver/windows/chromedriver.exe

serenity.report.encoding=UTF8
feature.file.encoding=UTF8
serenity.console.colors=true

serenity.take.screenshots = BEFORE_AND_AFTER_EACH_STEP
serenity.report.accessibility=true
chrome_preferences.download.default_directory=${user.dir}\\src\\test\\resources\\download

webdriver.chrome.driver=src/test/resources/driver/windows/chromedriver.exe
webdriver.base.url=https://demoqa.com/
webdriver.timeouts.implicitlywait=20000
webdriver.wait.for.timeout=20000